# Generated by Django 4.1.1 on 2023-01-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='funct',
            new_name='function',
        ),
        migrations.RemoveField(
            model_name='report',
            name='unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.report'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.unitname'),
        ),
    ]
