# Generated by Django 4.1.1 on 2023-01-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_remove_unit_report_report_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.asset'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.component'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.function'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.unitname'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='plant_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.planttag'),
        ),
    ]
