# Generated by Django 4.1.1 on 2023-03-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_alter_condition_entry_date_alter_unit_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='severityLevel',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('MED-HIGH', 'MED-HIGH'), ('MISSED', 'MISSED'), ('GOOD', 'GOOD')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='fault',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='recommendation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='analyst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.analyst'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.severity'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.technology'),
        ),
    ]
