# Generated by Django 4.1.1 on 2023-03-15 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_analyst_severity_technology_condition_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.severity'),
        ),
    ]
