# Generated by Django 4.1.1 on 2023-05-24 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_alter_condition_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.unit'),
        ),
    ]
