# Generated by Django 4.1.1 on 2023-05-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_alter_report_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='closed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fault_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.faultgroup'),
        ),
    ]
