# Generated by Django 4.1.1 on 2023-06-12 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_alter_unit_asset_alter_unit_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='plant_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.planttag'),
        ),
    ]
