# Generated by Django 4.1.1 on 2023-06-14 19:56

from django.db import migrations, models
import orgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_alter_unit_plant_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=orgs.models.Attachment.file_directory_path)),
                ('report_instance', models.ManyToManyField(blank=True, to='orgs.report')),
            ],
        ),
    ]
